### ISSUE TITLE
Error when running npm run dev

### ISSUE THREAD

**Issue by lchauvin** [Kitware/VolView#430]
Hello,

I am having some issue to run volview:

```
MacBook:VolView % npm run dev

> volview@4.1.0 dev
> vite

[vite-plugin-static-copy] Collected 166 items.                                                                                         11:44:19
                                                                                                                                       11:44:19
  VITE v4.3.9  ready in 680 ms

  ➜  Local:   http://localhost:8080/                                                                                                   11:44:19
  ➜  Network: use --host to expose                                                                                                     11:44:19
  ➜  press h to show help                                                                                                              11:44:19

 ERROR  Error: The following dependencies are imported but could not be resolved:                                                      11:44:19

  @kitware/vtk.js/types (imported by /Users/Lchauvin/code/VolView/src/components/tools/polygon/PolygonWidget2D.vue?id=0)

Are they installed?
    at file:///Users/Lchauvin/code/VolView/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44188:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/Lchauvin/code/VolView/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38
```

I just cloned the repo, run ```npm install``` then ```npm run dev```.

**Comment by lchauvin** [comment]
I believe in ```src/components/tools/polygon/PolygonWidget2D.vue``` and ```src/components/tools/BoundingRectangle.vue``` it should be ```@kitware/vtk.js/types.d``` instead of ```@kitware/vtk.js/types```.

Am I wrong ?

**Comment by PaulHax** [comment]
Good find.  Should be `import type` like this:

`import type { Vector3 } from '@kitware/vtk.js/types';`

Care to open a PR? =)
