### ISSUE TITLE
nii大文件（400MB）加载失败

### ISSUE THREAD

**Issue by Linst-inf** [Kitware/VolView#561]
![1710488506594](https://github.com/Kitware/VolView/assets/111498582/ee4d9557-bb07-4e6f-a7d0-71c9029406cb)
麻烦帮忙解答一下，谢谢！

**Comment by PaulHax** [comment]
For people to look into this, please publicly share a file that causes the error.

**Comment by Linst-inf** [comment]
好的，感谢，因为不支持上传nii格式，我压缩了一下。

**Comment by Linst-inf** [comment]
感谢回答，但是文件太大，无法上传。

**Comment by Linst-inf** [comment]
> 为了让人们调查此问题，请公开共享导致错误的文件。

感谢回答，但是文件太大了，无法上传。

**Comment by Linst-inf** [comment]
> For people to look into this, please publicly share a file that causes the error.

Could you please provide me with an email address so that I can send the files to your email.

**Comment by PaulHax** [comment]
paul.elliott@kitware.com

**Comment by Linst-inf** [comment]
> [paul.elliott@kitware.com](mailto:paul.elliott@kitware.com)
I have already sent it to your email. Looking forward to a reply. Thank you！

**Comment by PaulHax** [comment]
Got it!  Yes, it does not load in VolView with this error on the Javascript console:
```
loggers.ts:13 RangeError: Invalid initial number of values for array (origin)
    at macros2.js:554:13
    at Array.forEach (<anonymous>)
    at setArray (macros2.js:552:14)
    at Object.setGetArray (macros2.js:619:3)
    at extend (ImageData.js:354:9)
    at Object.constructor [as newInstance] (macros2.js:917:5)
    at convertItkToVtkImage (ITKHelper.js:87:34)
```

The loader says the file has 4 dimensions.  Must be a time series?  VolView does not handle 4D images.  Would be nice if it did or at least gave a nice error message to that effect.

**Comment by Linst-inf** [comment]
> 知道了！是的，它无法在 VolView 中加载，并在 Javascript 控制台上出现以下错误：
> 
> ```
> loggers.ts:13 RangeError: Invalid initial number of values for array (origin)
>     at macros2.js:554:13
>     at Array.forEach (<anonymous>)
>     at setArray (macros2.js:552:14)
>     at Object.setGetArray (macros2.js:619:3)
>     at extend (ImageData.js:354:9)
>     at Object.constructor [as newInstance] (macros2.js:917:5)
>     at convertItkToVtkImage (ITKHelper.js:87:34)
> ```
> 
> 加载器表示该文件有 4 个维度。一定是时间序列吗？VolView 不处理 4D 图像。如果它确实做到了或者至少给出了一个很好的错误消息，那就太好了。

Thank you for your help, but a smaller 4D file can be loaded. I will send it to you for review.
![image](https://github.com/Kitware/VolView/assets/111498582/b10dfe4c-fa1a-42c2-abb4-f0aa02697798)
[20220609170426_t1_gre_fsp_3d_sag_1mm.zip](https://github.com/Kitware/VolView/files/14680382/20220609170426_t1_gre_fsp_3d_sag_1mm.zip)

**Comment by Linst-inf** [comment]
> 知道了！是的，它无法在 VolView 中加载，并在 Javascript 控制台上出现以下错误：
> 
> ```
> loggers.ts:13 RangeError: Invalid initial number of values for array (origin)
>     at macros2.js:554:13
>     at Array.forEach (<anonymous>)
>     at setArray (macros2.js:552:14)
>     at Object.setGetArray (macros2.js:619:3)
>     at extend (ImageData.js:354:9)
>     at Object.constructor [as newInstance] (macros2.js:917:5)
>     at convertItkToVtkImage (ITKHelper.js:87:34)
> ```
> 
> 加载器表示该文件有 4 个维度。一定是时间序列吗？VolView 不处理 4D 图像。如果它确实做到了至少或者给出了一个很好的错误消息，那就太好了。
Thank you for your help, but a smaller 4D file can be loaded. I will send it to you for review.
![image](https://github.com/Kitware/VolView/assets/111498582/fe5c7128-e850-4b10-9f44-7fce05c385f0)
[test2.zip](https://github.com/Kitware/VolView/files/14680466/test2.zip)

**Comment by PaulHax** [comment]
For some reason the image reader library we are using shows the test2.zip file to hold a *3D* image:

```
  "imageType": {
    "dimension": 3,
    "componentType": "uint16",
    "pixelType": "Scalar",
    "components": 1
  },
  "origin": [
    81.04069519042969,
    116.38414764404297,
    -128.30361938476562
  ],
  "spacing": [
    0.6640629172325134,
    1,
    1
  ],
  "direction": "-0.9994939339115039,0.03180039970314527,0.0007813976456040354,-0.031809999592993764,-0.99919233310241,-0.024552098151576197...",
  "size": [
    256,
    220,
    256
  ],
```

**Comment by Linst-inf** [comment]
Could this be changed to support loading 4D files? thank you.

---- Replied Message ----
| From | Paul ***@***.***> |
| Date | 03/21/2024 21:48 |
| To | Kitware/VolView ***@***.***> |
| Cc | Linst-inf ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Kitware/VolView] Handle 4D time series nii files (Issue #561) |

For some reason the image reader library we are using shows the test2.zip file to hold a 3D image:

  "imageType": {
    "dimension": 3,
    "componentType": "uint16",
    "pixelType": "Scalar",
    "components": 1
  },
  "origin": [
    81.04069519042969,
    116.38414764404297,
    -128.30361938476562
  ],
  "spacing": [
    0.6640629172325134,
    1,
    1
  ],
  "direction": "-0.9994939339115039,0.03180039970314527,0.0007813976456040354,-0.031809999592993764,-0.99919233310241,-0.024552098151576197...",
  "size": [
    256,
    220,
    256
  ],

**Comment by PaulHax** [comment]
It could, but I'm not aware of this being on anyone's current TODO list.  We could support a community contributed PR or someone could fund Kitware for the work.
