### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by Linorman** [Kitware/VolView#640]
when I try to load a dicom zip, it occurred to give out errors:
RuntimeError: memory access out of bounds
pls help to solve it.

btw, can I use VolView to generate .obj files from dicom data and export them?

`RuntimeError: memory access out of bounds
    at wasm://wasm/0149037e
    at wasm://wasm/0149037e
    at wasm://wasm/0149037e
    at wasm://wasm/0149037e
    at wasm://wasm/0149037e
    at wasm://wasm/0149037e
    at wasm://wasm/0149037e
    at Module._main (cdn.jsdelivr.net/npm/@itk-wasm/dicom@6.0.0/dist/pipelines/read-image-dicom-file-series.js:8:98301)
    at Object.callMain (cdn.jsdelivr.net/npm/@itk-wasm/dicom@6.0.0/dist/pipelines/read-image-dicom-file-series.js:8:102622)
    at runPipelineEmscripten (run-pipeline-emscripten.js?v=bacb20ef:185:38)
useErrorMessage @ useErrorMessage.ts:13`

**Comment by Linorman** [comment]
> How large is your dicom zip file, and what kind of modality is it?
> 
> VolView cannot generate .obj files from dicom data. I assume you are looking to extract surfaces?

about 226 mb, and thanks for your reply about obj.

**Comment by floryst** [comment]
226mb shouldn't be a dealbreaker for VolView, unless your main machine is memory-restricted. What kind of DICOM images are in your zip?

**Comment by PaulHax** [comment]
If you can share the file or give more info, feel free to reopen this issue.
